title: VictoriaMetrics - the best long-term remote storage 
author: VictoriaMetrics
email: info@victoriametrics.com
description: >
  The best long-term remote storage 
  
plugins:
  - jekyll-remote-theme

remote_theme: jekyll/minima
google_analytics: UA-129683199-1
show_excerpts: true
