title: VictoriaMetrics
author: VictoriaMetrics
email: info@victoriametrics.com
description: >
  The Aspiring Monitoring Solution

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

google_analytics: UA-129683199-1

plugins:
  - github-pages


