title: VictoriaMetrics
author: VictoriaMetrics
email: info@victoriametrics.com
description: >
  The Aspiring Monitoring Solution

remote_theme: jekyll/minima
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: false

google_analytics: UA-129683199-1
plugins:
  - jekyll-remote-theme
  - jekyll-titles-from-headings
